---
- name: Restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: node_exporter
    state: restarted
  when: not ansible_check_mode
  listen: "Restart node_exporter"
