version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "America/New_York"
    assignees:
      - "tomswartz07"
    reviewers:
      - "tomswartz07"
