---
- hosts: all
  roles:
    - promtail
    - node_exporter
    - common

- hosts: clusterpi
  gather_facts: False
  vars:
    cluster: "clusterpi"
  roles:
    - clusterpi

- hosts: postgres
  gather_facts: False
  roles:
    - postgres
