---
# - name: Test ClusterPi
#  ansible.builtin.debug:
#    msg: "{{ ansible_nodename }} {{ user }}: {{ cluster }}"

- name: Set up local git dir
  file:
    path: "{{ ansible_facts['user_dir'] }}/git"
    state: directory
    mode: '0755'

- name: Install Git
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    state: present
    pkg:
      - git

- name: Pull Linux Configs
  git:
    repo: 'https://github.com/tomswartz07/linux-configs.git'
    dest: "{{ ansible_facts['user_dir'] }}/git/linux-configs"

- name: Set up local gitconfig
  file:
    src: "{{ ansible_facts['user_dir'] }}/git/linux-configs/gitconfig"
    dest: "{{ ansible_facts['user_dir'] }}/.gitconfig"
    state: link

- name: Set up config symlinks
  file:
    src: "{{ ansible_facts['user_dir'] }}/git/linux-configs/{{ item.src }}"
    dest: '{{ item.dest }}/{{ item.src }}'
    state: link
  loop:
    - {src: .zshrc, dest: "{{ ansible_facts['user_dir'] }}"}
    - {src: .vimrc, dest: "{{ ansible_facts['user_dir'] }}"}
    - {src: .vim, dest: "{{ ansible_facts['user_dir'] }}"}
    - {src: .tmux.conf, dest: "{{ ansible_facts['user_dir'] }}"}
    - {src: .dircolors, dest: "{{ ansible_facts['user_dir'] }}"}
    - {src: .config/nvim, dest: "{{ ansible_facts['user_dir'] }}"}

- name: Set up larger Swap size
  become: true
  when: _manage_swap
  template:
    src: dphys-swapfile.j2
    dest: /etc/dphys-swapfile
    owner: root
    group: root
    mode: 0644
  notify: Reload Swap
