---
#- name: Test ClusterPi
#  ansible.builtin.debug:
#    msg: "{{ ansible_nodename }} {{ user }}: {{ cluster }}"

- name: Ensure node_exporter is running
  become: yes
  service:
    name: "node_exporter"
    state: restarted
    enabled: yes
      #- name: Ensure old exporter is disabled
      #  become: yes
      #  service:
      #    name: "prometheus-node-exporter"
      #    state: stopped
      #    enabled: no
