---
- name: Ensure the PostgreSQL service is running
  become: yes
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: Get running PostgreSQL version
  become: yes
  become_user: "{{ postgresql_owner }}"
  command: psql -p {{ pg_port }} -Atc "SHOW server_version"
  register: running_version
  changed_when: false

- name: Get Recovery status
  become: yes
  become_user: "{{ postgresql_owner }}"
  command: psql -p {{ pg_port }} -Atc "select pg_is_in_recovery();"
  register: recovery_status
  changed_when: false
  when:
    - not pg_primary

- name: Fail if Replica is not in Recovery Mode
  fail:
    msg: "Replica is not in recovery mode."
  when:
    - not pg_primary
    - recovery_status.stdout == "f"
