name: Ansible-Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.2.1
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed
